### ISSUE TITLE
airflow style plugin mechanism

### ISSUE THREAD

**Issue by smorin** [smorin/flinkhose#6]

**Comment by maebert** [comment]
They just [crawl the plugin folder](https://github.com/apache/incubator-airflow/blob/master/airflow/plugins_manager.py) and load sources from there to discover plugins. http://pluginbase.pocoo.org seems a good off-the-shelf approach, too.

**Comment by smorin** [comment]
That sounds good, let's just look at both to understand how they work https://github.com/apache/incubator-airflow

**Comment by smorin** [comment]
This should allow for other configuration modules to be added to the project.  Like if we wanted to add spark instead of flink.  Basically we should be able to add new components to the flinkhose
